sudo: required

language: java

services:
  - docker

before_script:
  - docker-compose -f docker-compose.travis.yml up --build -d
  - docker ps -a
  - sleep 30

script: mvn clean verify

after_script:
  - docker-compose -f docker-compose.travis.yml down



