version: '3.3'

services:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    expose:
      - '6379'

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    expose:
      - '8081'
    depends_on:
      - redis

#  routes-service:
#    image: routes-service-image
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - mysql
#      - redis
#    ports:
#      - 8080:8080
#    volumes:
#      - /data/routes-service-app

